services:
  api:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    env_file: 
      - .env
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
