"""
This type stub file was generated by pyright.
"""

from .api_jwt import PyJWT, decode, encode, get_unverified_header, register_algorithm, unregister_algorithm
from .api_jws import PyJWS
from .exceptions import DecodeError, ExpiredSignature, ExpiredSignatureError, ImmatureSignatureError, InvalidAudience, InvalidAudienceError, InvalidIssuedAtError, InvalidIssuer, InvalidIssuerError, InvalidTokenError, MissingRequiredClaimError

"""
JSON Web Token implementation

Minimum implementation based on this spec:
http://self-issued.info/docs/draft-jones-json-web-token-01.html
"""
__title__ = ...
__version__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
