"""
This type stub file was generated by pyright.
"""

class InvalidTokenError(Exception):
    ...


class DecodeError(InvalidTokenError):
    ...


class ExpiredSignatureError(InvalidTokenError):
    ...


class InvalidAudienceError(InvalidTokenError):
    ...


class InvalidIssuerError(InvalidTokenError):
    ...


class InvalidIssuedAtError(InvalidTokenError):
    ...


class ImmatureSignatureError(InvalidTokenError):
    ...


class InvalidKeyError(Exception):
    ...


class InvalidAlgorithmError(InvalidTokenError):
    ...


class MissingRequiredClaimError(InvalidTokenError):
    def __init__(self, claim) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


ExpiredSignature = ExpiredSignatureError
InvalidAudience = InvalidAudienceError
InvalidIssuer = InvalidIssuerError
