"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from collections.abc import Mapping
from typing import Any, Callable, Optional, TypeVar, Union
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey, RSAPublicKey

_AJWK = TypeVar("_AJWK", bound="AbstractJWKBase")
_T = TypeVar("_T")
class AbstractJWKBase(ABC):
    @abstractmethod
    def get_kty(self) -> str:
        ...
    
    @abstractmethod
    def get_kid(self) -> str:
        ...
    
    @abstractmethod
    def is_sign_key(self) -> bool:
        ...
    
    @abstractmethod
    def sign(self, message: bytes, **options) -> bytes:
        ...
    
    @abstractmethod
    def verify(self, message: bytes, signature: bytes, **options) -> bool:
        ...
    
    @abstractmethod
    def to_dict(self, public_only: bool = ...) -> dict[str, str]:
        ...
    
    @classmethod
    @abstractmethod
    def from_dict(cls: type[_AJWK], dct: dict[str, object]) -> _AJWK:
        ...
    


class OctetJWK(AbstractJWKBase):
    def __init__(self, key: bytes, kid=..., **options) -> None:
        ...
    
    def get_kty(self): # -> Literal['oct']:
        ...
    
    def get_kid(self): # -> None:
        ...
    
    def is_sign_key(self) -> bool:
        ...
    
    def sign(self, message: bytes, **options) -> bytes:
        ...
    
    def verify(self, message: bytes, signature: bytes, **options) -> bool:
        ...
    
    def to_dict(self, public_only=...): # -> dict[str, str | Any]:
        ...
    
    @classmethod
    def from_dict(cls, dct): # -> Self:
        ...
    


class RSAJWK(AbstractJWKBase):
    """
    https://tools.ietf.org/html/rfc7518.html#section-6.3.1
    """
    def __init__(self, keyobj: Union[RSAPrivateKey, RSAPublicKey], **options) -> None:
        ...
    
    def is_sign_key(self) -> bool:
        ...
    
    def sign(self, message: bytes, **options) -> bytes:
        ...
    
    def verify(self, message: bytes, signature: bytes, **options) -> bool:
        ...
    
    def get_kty(self): # -> Literal['RSA']:
        ...
    
    def get_kid(self): # -> None:
        ...
    
    def to_dict(self, public_only=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def from_dict(cls, dct): # -> Self:
        ...
    


def supported_key_types() -> dict[str, type[AbstractJWKBase]]:
    ...

def jwk_from_dict(dct: Mapping[str, Any]) -> AbstractJWKBase:
    ...

PublicKeyLoaderT = Union[str, Callable[[bytes, object], object]]
PrivateKeyLoaderT = Union[str, Callable[[bytes, Optional[str], object], object]]
_Loader = TypeVar("_Loader", PublicKeyLoaderT, PrivateKeyLoaderT)
_C = TypeVar("_C", bound=Callable[..., Any])
def jwk_from_bytes_argument_conversion(func: _C) -> _C:
    ...

@jwk_from_bytes_argument_conversion
def jwk_from_private_bytes(content: bytes, private_loader: PrivateKeyLoaderT, *, password: Optional[str] = ..., backend: Optional[object] = ..., options: Optional[Mapping[str, object]] = ...) -> AbstractJWKBase:
    """This function is meant to be called from jwk_from_bytes"""
    ...

@jwk_from_bytes_argument_conversion
def jwk_from_public_bytes(content: bytes, public_loader: PublicKeyLoaderT, *, backend: Optional[object] = ..., options: Optional[Mapping[str, object]] = ...) -> AbstractJWKBase:
    """This function is meant to be called from jwk_from_bytes"""
    ...

def jwk_from_bytes(content: bytes, private_loader: PrivateKeyLoaderT, public_loader: PublicKeyLoaderT, *, private_password: Optional[str] = ..., backend: Optional[object] = ..., options: Optional[Mapping[str, object]] = ...) -> AbstractJWKBase:
    ...

def jwk_from_pem(pem_content: bytes, private_password: Optional[str] = ..., options: Optional[Mapping[str, object]] = ...) -> AbstractJWKBase:
    ...

def jwk_from_der(der_content: bytes, private_password: Optional[str] = ..., options: Optional[Mapping[str, object]] = ...) -> AbstractJWKBase:
    ...

