"""
This type stub file was generated by pyright.
"""

from collections import UserList
from typing import TYPE_CHECKING
from .jwk import AbstractJWKBase

if TYPE_CHECKING:
    UserListBase = UserList[AbstractJWKBase]
else:
    ...
class JWKSet(UserListBase):
    def filter_keys(self, kid=..., kty=...): # -> list[AbstractJWKBase]:
        ...
    
    def to_dict(self, public_only=...): # -> dict[str, list[dict[str, str]]]:
        ...
    
    @classmethod
    def from_dict(cls, dct): # -> Self:
        ...
    


