"""
This type stub file was generated by pyright.
"""

from typing import AbstractSet, Optional
from .jwk import AbstractJWKBase

__all__ = ["JWS"]
class JWS:
    def __init__(self) -> None:
        ...
    
    def encode(self, message: bytes, key: Optional[AbstractJWKBase] = ..., alg=..., optional_headers: Optional[dict[str, str]] = ...) -> str:
        ...
    
    def decode(self, message: str, key: Optional[AbstractJWKBase] = ..., do_verify=..., algorithms: Optional[AbstractSet[str]] = ...) -> bytes:
        ...
    


