"""
This type stub file was generated by pyright.
"""

from typing import AbstractSet, Any, Optional
from .jwk import AbstractJWKBase

class JWT:
    def __init__(self) -> None:
        ...
    
    def encode(self, payload: dict[str, Any], key: Optional[AbstractJWKBase] = ..., alg=..., optional_headers: Optional[dict[str, str]] = ...) -> str:
        ...
    
    def decode(self, message: str, key: Optional[AbstractJWKBase] = ..., do_verify=..., algorithms: Optional[AbstractSet[str]] = ..., do_time_check: bool = ...) -> dict[str, Any]:
        ...
    


