"""
This type stub file was generated by pyright.
"""

def force_unicode(value):
    ...

def force_bytes(value): # -> str:
    ...

def base64url_decode(input): # -> bytes:
    ...

def base64url_encode(input): # -> bytes:
    ...

def to_base64url_uint(val): # -> bytes:
    ...

def from_base64url_uint(val): # -> int:
    ...

def merge_dict(original, updates):
    ...

def number_to_bytes(num, num_bytes): # -> bytes:
    ...

def bytes_to_number(string): # -> int:
    ...

def der_to_raw_signature(der_sig, curve): # -> bytes:
    ...

def raw_to_der_signature(raw_sig, curve): # -> bytes:
    ...

