"""
This type stub file was generated by pyright.
"""

import click
from flask.cli import with_appcontext

@click.command()
@click.option("-f", "--file", type=click.File("w"), default="-")
@click.option("-e", "--endpoint", default=None)
@with_appcontext
def generate_api_schema(file, endpoint):
    """Generate the swagger schema for your api."""
    ...

